routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::namespace('Edit')->group(function () {
    // Controllers Within The "App\Http\Controllers\Edit" Namespace
    Route::get('edit/home', 'HomeController@index')->name('home');

    Route::resource('edit/quotes', 'QuotesController');
    Route::resource('edit/pictures', 'PicturesController');
    Route::resource('edit/authors', 'AuthorsController');

});

app/Quote.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Quote extends Model
{
    protected $fillable = [
        'name',
        'author_id',
        'text',
        'date',
    ];

    /**
     * Связь с Picture
     */
    public function author()
    {
        return $this->hasOne('App\Author', 'id', 'author_id');
    }
}

app/Http/Controllers/Edit/AuthorsController.php
<?php

namespace App\Http\Controllers\Edit;

use App\Author;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authors = Author::with('picture')->get();

        return view('edit.authors.index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('edit.authors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $request->validate([
            'name'=>'required',
            'surname'=> 'required',
        ]);

        $author = new Author([
            'name' => $request->get('name'),
            'surname'=> $request->get('surname'),
        ]);

        if ($image = $request->file('image')) {
            $author->setImage($image);
        }

        $author->save();

        return redirect()->route('authors.show', ['author' => $author->id])->with('success', 'Автор создан');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $author = Author::find($id);
        return view('edit.authors.show', compact('author'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $author = Author::find($id);
        return view('edit.authors.edit', compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'surname'=> 'required',
        ]);
        
        $author = Author::find($id);
        $author->name = $request->get('name');
        $author->surname = $request->get('surname');

        if ($image = $request->file('image')) {
            $author->setImage($image);
            //$author->save();
        }

        $author->save();

        return redirect()->route('authors.show', ['author' => $author->id])->with('success', 'Автор обновлен');
        //return redirect('/edit/authors', )->with('success', 'Автор обновлен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $author = Author::find($id);
        $author->delete();

     return redirect('/edit/authors')->with('success', 'Автор удален');
    }
}

app/Http/Controllers/Edit/HomeController.php
<?php

namespace App\Http\Controllers\Edit;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Edit/PicturesController.php
<?php

namespace App\Http\Controllers\Edit;

use App\Picture;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PicturesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $pictures = Picture::all();

        return view('edit.pictures.index', compact('pictures'));


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Picture  $picture
     * @return \Illuminate\Http\Response
     */
    public function show(Picture $picture)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Picture  $picture
     * @return \Illuminate\Http\Response
     */
    public function edit(Picture $picture)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Picture  $picture
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Picture $picture)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Picture  $picture
     * @return \Illuminate\Http\Response
     */
    public function destroy(Picture $picture)
    {
        //
    }
}

app/Http/Controllers/Edit/QuotesController.php
<?php

namespace App\Http\Controllers\Edit;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Quote;
use App\Author;

class QuotesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quotes = Quote::all();

        return view('edit.quotes.index', compact('quotes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $authors = Author::getList();
        // dd($authors);

        return view('edit.quotes.create', compact('authors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'text'=> 'required',
        ]);

        $quote = new Quote([
            'name' => $request->get('name'),
            'text'=> $request->get('text'),
            'date'=> $request->get('date'),
            'author_id'=> $request->get('author'),
        ]);

        $quote->save();

        return redirect()->route('quotes.show', ['quote' => $quote->id])->with('success', 'Цитата создана');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $quote = Quote::find($id);
        return view('edit.quotes.show', compact('quote'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $quote = Quote::find($id);
        $authors = Author::getList();
        return view('edit.quotes.edit', compact('quote', 'authors'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'text'=> 'required',
        ]);
        
        $quote = Quote::find($id);
        $quote->name = $request->get('name');
        $quote->text = $request->get('text');
        $quote->author_id = $request->get('author');
        $quote->date = $request->get('date');

        $quote->save();

        return redirect()->route('quotes.show', ['quote' => $quote->id])->with('success', 'Цитата обновлена');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $quote = Quote::find($id);
        $quote->delete();

        return redirect()->route('quotes.index')->with('success', 'Цитата удалена');
    }
}

resources/views/edit/quotes/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('home') }}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ route('quotes.index') }}">Цитаты</a></li>
        <li class="breadcrumb-item active" aria-current="page">Создать</li>
    </ol>
    </nav>

    <h1>Создать Автора</h1>

    <div class="edit-quotes-create">

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif

        <form method="post" action="{{ route('quotes.store') }}">

            <div class="form-group">
                <label for="input-name">Автор:</label>
                <select class="form-control" name="author">
                    <option value="" disabled selected>Автор</option>
                    @foreach ($authors as $author)
                        <option value="{{ $author['id'] }}" > {{ $author['name']}} {{ $author['surname'] }}  </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="input-name">Название:</label>
                <input type="text" class="form-control" name="name"/>
            </div>

            <div class="form-group">
                <label for="input-name">Текст:</label>
                <textarea name="text" class="form-control" cols="30" rows="10"></textarea>
            </div>

            <div class="form-group">
                <label for="input-surname">Дата:</label>
                <input type="date" class="form-control" name="date"/>
            </div>
            @csrf
            <button type="submit" class="btn btn-success">Создать</button>

        </form>

    </div>
</div>
@endsection

resources/views/edit/quotes/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('home') }}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ route('quotes.index') }}">Цитаты</a></li>
        <li class="breadcrumb-item"><a href="{{ route('quotes.show', $quote->id) }}">{{ $quote->id }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Изменить</li>
    </ol>
    </nav>

    <h1>Изменить цитату</h1>

    <div class="edit-quotes-edit">

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div><br />
        @endif

        <form method="post" action="{{ route('quotes.update', $quote->id) }}">

            @method('PATCH')
            @csrf


            <div class="form-group">
                <label for="input-name">Автор:</label>
                <select class="form-control" name="author">
                    <option value="" disabled selected>Автор</option>
                    @foreach ($authors as $author)
                        <option value="{{ $author['id'] }}" <?= $quote->author_id == $author['id'] ? 'selected' : '' ?>> {{ $author['name']}} {{ $author['surname'] }}  </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="input-name">Название:</label>
                <input type="text" class="form-control" name="name" value="{{ $quote->name }}"/>
            </div>

            <div class="form-group">
                <label for="input-name">Текст:</label>
                <textarea name="text" class="form-control" cols="30" rows="10">{{ $quote->text }}</textarea>
            </div>

            <div class="form-group">
                <label for="input-surname">Дата:</label>
                <input type="date" class="form-control" name="date" value="{{ $quote->date }}"/>
            </div>
            @csrf
            <button type="submit" class="btn btn-success">Изменить</button>

        </form>

    </div>
</div>
@endsection

resources/views/edit/quotes/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="edit-quotes-index">

            <h1>Цитаты  </h1>

            @if(session()->get('success'))
                <div class="alert alert-success">
                {{ session()->get('success') }}  
                </div><br />
            @endif
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                    <td>ID</td>
                    <td>Название</td>
                    <td>Дата</td>
                    <td>Текст</td>
                    <td colspan="2">Действия</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($quotes as $quote)
                    <tr>
                        <td>{{$quote->id}}</td>
                        <td>{{$quote->name}}</td>
                        <td>{{$quote->date}}</td>
                        <td>{{$quote->text}}</td>
                        <td><a href="{{ route('quotes.edit',$quote->id)}}" class="btn btn-primary">Изменить</a></td>
                        <td>
                            <form action="{{ route('quotes.destroy', $quote->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">Удалить</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <a href="{{ route('quotes.create')}}" class="btn btn-success">Создать</a>
        </div>
    </div>
    
@endsection

resources/views/edit/quotes/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="edit-quotes-index">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">Главная</a></li>
                <li class="breadcrumb-item"><a href="{{ route('authors.index') }}">Авторы</a></li>
                <li class="breadcrumb-item active">{{ $quote->id }}</li>
            </ol>

            <h1>Цитата: {{ $quote->name }}</h1>

            <div class="form-group">

                <a href="{{ route('quotes.edit',$quote->id)}}" class="btn btn-primary">Изменить</a>
                        
                <form class="d-inline-block" action="{{ route('quotes.destroy', $quote->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">Удалить</button>
                </form>
                    
            </div>

            <table class="table table-striped table-bordered">
                <tbody>
                <tr>
                    <tr>
                        <td>ID</td>
                        <td>{{$quote->id}}</td>
                    </tr>
                    <tr>
                        <th>Имя</th> 
                        <td>{{$quote->name}}</td>        
                    </tr>
                    <tr>
                        <th>Автор</th> 
                        <td>{{ $quote->author->name }} {{ $quote->author->surname }}</td> 
                    </tr>
                    <tr>
                        <th>Дата</th>
                        <td>{{$quote->date}}</td> 
                    </tr>
                    <tr>
                        <th>Текст</th>
                        <td>{{$quote->text}}</td> 
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    @endsection